name: Big Dawg Deploy

on:
  push:
    branches: [main] # Or 'master' if you're old school
  workflow_dispatch:

permissions:
  contents: read
  pages: write
  id-token: write

concurrency:
  group: "pages"
  cancel-in-progress: true

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: 20
          cache: 'npm'
      - name: Install
        run: npm ci
      - name: Build that thing
        run: npm run build
      - name: Upload
        uses: actions/upload-pages-artifact@v3
        with:
          path: './dist' # Vite outputs here by default
          
      # 1. Fix the 404s (Copy index to 404)
      # ⚠️ Notice the path is now 'build/client', NOT 'dist'
      - name: Fix 404s
        run: cp build/client/index.html build/client/404.html

      # 2. Upload the correct folder
      - name: Upload Artifact
        uses: actions/upload-pages-artifact@v3
        with:
          path: './build/client' # 👈 THIS CHANGED

  deploy:
    environment:
      name: github-pages
      url: ${{ steps.deployment.outputs.page_url }}
    runs-on: ubuntu-latest
    needs: build
    steps:
      - name: Go Live
        id: deployment
        uses: actions/deploy-pages@v4